# Numpy
    + 대규모 다차원 배열을 쉽게 처리할 수 있도록 도와주는 외부 모듈
    + array 라는 자료형을 사용

In [1]:
# numpy의 선언과 예제
import numpy as np

a = [1,2,3,4,5]
# numpy 를 통해 배열 
b = np.array(a)
print(b)

[1 2 3 4 5]


* 행렬 연산을 지원

In [2]:
# 덧셈
import numpy as np

a = [1,2,3,4,5]
# numpy 를 통해 배열 
b = np.array(a)

print(a+a)
print(b+b)
print(b*3)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[ 2  4  6  8 10]
[ 3  6  9 12 15]


* 다차원 행렬 및 행렬 연산 지원(2차원 배열)

In [4]:
a = [[1,1,1], [2,2,2],[3,3,3]]
b = np.array(a)

print(a)
print(b)
print(b.shape)
print(b*3)

[[1, 1, 1], [2, 2, 2], [3, 3, 3]]
[[1 1 1]
 [2 2 2]
 [3 3 3]]
(3, 3)
[[3 3 3]
 [6 6 6]
 [9 9 9]]


* 리스트보다 다양한 방식의 인덱싱을 지원
    + 리스트 : 요소를 기준으로 인덱싱
    + numpy의 행렬 : 위치를(범위) 기준으로 인덱싱
        - \[ : ,2\] : 2index 열에 있는 모든 값
        - \[1, :2\] : 1index 행에 있는 2열 까지의 값

In [8]:
print(b, '\n')
print(b[:,2], '\n')
print(b[1,:2])

[[1 1 1]
 [2 2 2]
 [3 3 3]] 

[1 2 3] 

[2 2]


# pandas
 + 행과 열로 이루어진 테이터를 쉽게 다룰수 있돌고 외부모듈, 대용량의 데이터를 처리하는데 요이하다.
    

* Seris자료형
    + 별도의 인덱스 , 별도의. 값을 출력하게 설정할 수 있다. (사용자 임의로 index를 지정할 수 있다.)
* DataFirame 자료형
    + 행, 열 로 데이터를 전처리 하여 손쉽게 분석할 수 있도록 하는 기능이 있는 자료형

In [13]:
import pandas as pd
a = pd.Series([1,2,3,4])
print(a)

0    1
1    2
2    3
3    4
dtype: int64


In [17]:
a = pd.Series([1,2,3,4], index = ['a','b','c','d'])
print(a)
print(a.index)

a    1
b    2
c    3
d    4
dtype: int64
Index(['a', 'b', 'c', 'd'], dtype='object')


 * 파이썬 사전을 Serise로 변환

In [20]:
import pandas as pd

dic = {'a' : 1, 'b' : 2, 'c' : 3}
a = pd.Series(dic)
print(a)

a    1
b    2
c    3
dtype: int64


* Numpy의 array 자료형도 변형가능

In [21]:
import pandas as pd
import numpy as np

a = np.array([1,2,3,4])
b = pd.Series(a)
print(b)

0    1
1    2
2    3
3    4
dtype: int32


* DataFrame
    + 행과 열로 이루어진 자료형
    

In [26]:
import pandas as pd
a = pd.Series({'a' :[1,1,1], 'b' : [2,2,2], 'c' : [3,3,3]})
print(a)

print()

b = pd.DataFrame({'a' :[1,1,1], 'b' : [2,2,2], 'c' : [3,3,3]})
print(b)

a    [1, 1, 1]
b    [2, 2, 2]
c    [3, 3, 3]
dtype: object

   a  b  c
0  1  2  3
1  1  2  3
2  1  2  3


In [27]:
# 특정 컬럼의 값을 일괄 변경

b = pd.DataFrame({'a' :[1,1,1], 'b' : [2,2,2], 'c' : [3,3,3]})

b['b'] = [5,6,7]
print(b)

   a  b  c
0  1  5  3
1  1  6  3
2  1  7  3


In [32]:
# index를 지정 (명칭 변경)

b = pd.DataFrame({'a' :[1,1,1], 'b' : [5,6,7], 'c' : [3,3,3]})

b.index =['A', 'B', 'C']
b.columns = ['xx','yy','zz']
print(b)

   xx  yy  zz
A   1   5   3
B   1   6   3
C   1   7   3


In [33]:
# 컬럼의 키로 데이터 표현하기
print(b['zz'])

A    3
B    3
C    3
Name: zz, dtype: int64


In [36]:
# index 행의 데이터 표현하기
print(b.iloc[0])

print()

print(b.loc['A'])

xx    1
yy    5
zz    3
Name: A, dtype: int64

xx    1
yy    5
zz    3
Name: A, dtype: int64


In [37]:
print(b.describe())

        xx   yy   zz
count  3.0  3.0  3.0
mean   1.0  6.0  3.0
std    0.0  1.0  0.0
min    1.0  5.0  3.0
25%    1.0  5.5  3.0
50%    1.0  6.0  3.0
75%    1.0  6.5  3.0
max    1.0  7.0  3.0


In [40]:
print(b.sum()) # 컬럼의 모든 값을 더함
print(b.sum(axis=1)) # 행의 모든 값을 더함

xx     3
yy    18
zz     9
dtype: int64
A     9
B    10
C    11
dtype: int64


In [41]:
# unique()
# set 과 마찬가지로 중복을 제거하고 표현
print(b.iloc[0].unique())
print(b['xx'].unique())

[1 5 3]
[1]
